"""laup42 told me to do it like this.

Revision ID: 04e65257e272
Revises: 9f069d06a93d
Create Date: 2025-05-03 01:33:58.902904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04e65257e272'
down_revision = '9f069d06a93d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('big_pixel_factor', sa.Integer(), nullable=True))
        batch_op.drop_column('big_pixel_size')

    with op.batch_alter_table('pixel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dim_x', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('dim_y', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pixel', schema=None) as batch_op:
        batch_op.drop_column('dim_y')
        batch_op.drop_column('dim_x')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('big_pixel_size', sa.INTEGER(), nullable=True))
        batch_op.drop_column('big_pixel_factor')

    # ### end Alembic commands ###
