"""Add changes

Revision ID: 14051d3d8ef7
Revises: b053f87e5d9c
Create Date: 2025-05-04 23:12:46.960484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14051d3d8ef7'
down_revision = 'b053f87e5d9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('color_id', sa.Integer(), nullable=True),
    sa.Column('pixel_id', sa.Integer(), nullable=True),
    sa.Column('happens_at_same_time_as_previous_change', sa.Boolean(), nullable=True),
    sa.Column('change_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['color_id'], ['color.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['pixel_id'], ['pixel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('change')
    # ### end Alembic commands ###
