"""Add event table

Revision ID: 39879834003e
Revises: 
Create Date: 2025-04-30 00:19:44.058134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39879834003e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=65), nullable=True),
    sa.Column('slug', sa.String(length=15), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event')
    # ### end Alembic commands ###
