"""Add submit method table

Revision ID: 544e7c3c58e1
Revises: 59bdd99fe826
Create Date: 2025-06-04 20:59:48.291878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '544e7c3c58e1'
down_revision = '59bdd99fe826'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submit_method',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=65), nullable=True),
    sa.Column('file_name', sa.String(length=15), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submit_method')
    # ### end Alembic commands ###
