"""Add user and source to changes

Revision ID: 59bdd99fe826
Revises: 14051d3d8ef7
Create Date: 2025-05-04 23:24:50.434938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59bdd99fe826'
down_revision = '14051d3d8ef7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('change', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('source', sa.String(length=64), nullable=True))
        batch_op.create_foreign_key('changes_from_user', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('change', schema=None) as batch_op:
        batch_op.drop_constraint('changes_from_user', type_='foreignkey')
        batch_op.drop_column('source')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
