"""remane dim_x and dim_y to reflect that they are not in adifferent dimension, but in fact, on the canvas.

Revision ID: 6d141580a860
Revises: 04e65257e272
Create Date: 2025-05-03 01:50:04.441520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d141580a860'
down_revision = '04e65257e272'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pixel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('canv_x', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('canv_y', sa.Integer(), nullable=True))
        batch_op.drop_column('dim_x')
        batch_op.drop_column('dim_y')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pixel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dim_y', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('dim_x', sa.INTEGER(), nullable=True))
        batch_op.drop_column('canv_y')
        batch_op.drop_column('canv_x')

    # ### end Alembic commands ###
