"""Add pixel size options

Revision ID: 95ca1bd6b2f6
Revises: 39879834003e
Create Date: 2025-05-01 23:11:50.504651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95ca1bd6b2f6'
down_revision = '39879834003e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pixel_width', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pixel_height', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('inner_pixel_dimensions', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('inner_pixel_dimensions')
        batch_op.drop_column('pixel_height')
        batch_op.drop_column('pixel_width')

    # ### end Alembic commands ###
