"""Add public/private api token fields

Revision ID: b053f87e5d9c
Revises: 6d141580a860
Create Date: 2025-05-03 02:49:46.590035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b053f87e5d9c'
down_revision = '6d141580a860'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_public_token', sa.String(length=24), nullable=True))
        batch_op.add_column(sa.Column('api_private_token', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('api_private_token')
        batch_op.drop_column('api_public_token')

    # ### end Alembic commands ###
