"""Add colors

Revision ID: cebf495b2c13
Revises: 95ca1bd6b2f6
Create Date: 2025-05-01 23:34:04.313122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cebf495b2c13'
down_revision = '95ca1bd6b2f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('color',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hexcode', sa.String(length=7), nullable=True),
    sa.Column('hue', sa.String(length=1), nullable=True),
    sa.Column('lightness', sa.String(length=1), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('color')
    # ### end Alembic commands ###
