"""Add default options to submit methods

Revision ID: ff2e85782b2f
Revises: 6ce58ab2f2d1
Create Date: 2025-06-04 21:01:58.326018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff2e85782b2f'
down_revision = '6ce58ab2f2d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submit_method', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_options', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submit_method', schema=None) as batch_op:
        batch_op.drop_column('default_options')

    # ### end Alembic commands ###
